FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD HelloWorld.jar /opt/HelloWorld/
EXPOSE 8080
WORKDIR /opt/HelloWorld/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "HelloWorld.jar"]
